version: "3.2"
name: sso_service
services:
  postgres:
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sso
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pswd
    container_name: pg
    hostname: db
    networks:
      - pgnet
    volumes:
      - pg:/var/lib/postgresql/data
    image: postgres:16.2-alpine3.19
    user: postgres
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-d",
          "$POSTGRES_DB",
          "-U",
          "$POSTGRES_USER"
        ]
      interval: 2s
      timeout: 2s
      retries: 8
  migrate:
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pgnet
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://usr:pswd@db:5432/sso?sslmode=disable",
        "up"
      ]
    image: migrate/migrate
  sso:
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - 8080:8080
      - 5055:5055
    environment:
      - TOKEN_SECRET=secret123
      - CONFIG_PATH=./configs/local.yaml
      - CONN=postgres://usr:pswd@db:5432/sso
    container_name: sso
    networks:
      - pgnet
    build: .
networks:
  pgnet:
    driver: bridge
volumes:
  pg:
