version: '3'
tasks:
  generate_protoc:
    aliases:
      - gen
      - generate
      - protoc
    desc: generates new .go files from .proto in ./proto directory
    cmd: protoc --proto_path=./proto --go_out=./gen --go_opt=paths=source_relative --go-grpc_out=./gen --go-grpc_opt=paths=source_relative sso.proto
  run_tests:
    aliases:
      - tests
    desc: runs functional tests TODO
    cmd: echo 'Not implemented!'
  run_sso:
    aliases:
      - run
      - sso
    desc: runs cmd/sso/main.go with all flags
    cmd: go run cmd/sso/main.go --config-path=./config/local.yaml
  run_migrator:
    aliases:
      - migrator
    desc: runs cmd/migrator/main.go
    cmd: go run cmd/migrator/main.go
  test:
    cmd: echo 'Hello, world!'